export const descriptions = {
  // Animations
  'Animations/AnimatedContent':
    'Wrapper that animates any children on scroll or mount with configurable direction, distance, duration and easing.',
  'Animations/BlobCursor': 'Organic blob cursor that smoothly follows the pointer with inertia and elastic morphing.',
  'Animations/ClickSpark': 'Creates particle spark bursts at click position.',
  'Animations/Crosshair': 'Custom crosshair cursor with tracking, and link hover effects.',
  'Animations/Cubes': '3D rotating cube cluster. Supports auto-rotation or hover interaction.',
  'Animations/ElectricBorder': 'Jittery electric energy border with animated arcs, glow and adjustable intensity.',
  'Animations/FadeContent': 'Simple directional fade / slide entrance wrapper with threshold-based activation.',
  'Animations/GlareHover': 'Adds a realistic moving glare highlight on hover over any element.',
  'Animations/GradualBlur': 'Progressively un-blurs content based on scroll or trigger creating a cinematic reveal.',
  'Animations/ImageTrail': 'Cursor-based image trail with several built-in variants.',
  'Animations/LogoLoop': 'Continuously looping marquee of brand or tech logos with seamless repeat and hover pause.',
  'Animations/Magnet': 'Elements magnetically ease toward the cursor then settle back with spring physics.',
  'Animations/MagnetLines': 'Animated field lines bend toward the cursor.',
  'Animations/MetaBalls': 'Liquid metaball blobs that merge and separate with smooth implicit surface animation.',
  'Animations/MetallicPaint': 'Liquid metallic paint shader which can be applied to SVG elements.',
  'Animations/Noise': 'Animated film grain / noise overlay adding subtle texture and motion.',
  'Animations/PixelTrail': 'Pixelated cursor trail emitting fading squares with retro digital feel.',
  'Animations/PixelTransition': 'Pixel dissolve transition for content reveal on hover.',
  'Animations/Ribbons': 'Flowing responsive ribbons/cursor trail driven by physics and pointer motion.',
  'Animations/ShapeBlur': 'Morphing blurred geometric shape. The effect occurs on hover.',
  'Animations/SplashCursor': 'Liquid splash burst at cursor with curling ripples and waves.',
  'Animations/StarBorder': 'Animated star / sparkle border orbiting content with twinkle pulses.',
  'Animations/StickerPeel': 'Sticker corner lift + peel interaction using 3D transform and shadow depth.',
  'Animations/TargetCursor': 'A cursor follow animation with 4 corners that lock onto targets.',
  'Animations/LaserFlow': 'Dynamic laser light that flows onto a surface, customizable effect.',

  // Text Animations
  'TextAnimations/ASCIIText': 'Renders text with an animated ASCII background for a retro feel.',
  'TextAnimations/BlurText': 'Text starts blurred then crisply resolves for a soft-focus reveal effect.',
  'TextAnimations/CircularText': 'Layouts characters around a circle with optional rotation animation.',
  'TextAnimations/CountUp': 'Animated number counter supporting formatting and decimals.',
  'TextAnimations/CurvedLoop': 'Flowing looping text path along a customizable curve with drag interaction.',
  'TextAnimations/DecryptedText': 'Hacker-style decryption cycling random glyphs until resolving to real text.',
  'TextAnimations/FallingText': 'Characters fall with gravity + bounce creating a playful entrance.',
  'TextAnimations/FuzzyText': 'Vibrating fuzzy text with controllable hover intensity.',
  'TextAnimations/GlitchText': 'RGB split and distortion glitch effect with jitter effects.',
  'TextAnimations/GradientText': 'Animated gradient sweep across live text with speed and color control.',
  'TextAnimations/RotatingText': 'Cycles through multiple phrases with 3D rotate / flip transitions.',
  'TextAnimations/ScrambledText': 'Detects cursor position and applies a distortion effect to text.',
  'TextAnimations/ScrollFloat': 'Text gently floats / parallax shifts on scroll.',
  'TextAnimations/ScrollReveal': 'Text gently unblurs and reveals on scroll.',
  'TextAnimations/ScrollVelocity': "Text marquee animatio - speed and distortion scale with user's scroll velocity.",
  'TextAnimations/ShinyText': 'Metallic sheen sweeps across text producing a reflective highlight.',
  'TextAnimations/SplitText': 'Splits text into characters / words for staggered entrance animation.',
  'TextAnimations/TextCursor': 'Make any text element follow your cursor, leaving a trail of copies behind it.',
  'TextAnimations/TextPressure': 'Characters scale / warp interactively based on pointer pressure zone.',
  'TextAnimations/TextTrail': "3D trail effect that follows the cursor and changes the text's appearance.",
  'TextAnimations/TextType': 'Typewriter effect with blinking cursor and adjustable typing cadence.',
  'TextAnimations/TrueFocus': 'Applies dynamic blur / clarity based over a series of words in order.',
  'TextAnimations/VariableProximity': 'Letter styling changes continuously with pointer distance mapping.',
  'TextAnimations/Shuffle': 'Animated text reveal where characters shuffle before settling.',

  // Components
  'Components/AnimatedList': 'List items enter with staggered motion variants for polished reveals.',
  'Components/BounceCards': 'Cards bounce that bounce in on mount.',
  'Components/BubbleMenu': 'Floating circular expanding menu with staggered item reveal.',
  'Components/CardNav': 'Expandable navigation bar with card panels revealing nested links.',
  'Components/CardSwap': 'Cards animate position swapping with smooth layout transitions.',
  'Components/Carousel': 'Responsive carousel with touch gestures, looping and transitions.',
  'Components/ChromaGrid': 'A responsive grid of grayscale tiles. Hovering the grid reaveals their colors.',
  'Components/CircularGallery': 'Circular orbit gallery rotating images.',
  'Components/Counter': 'Flexible animated counter supporting increments + easing.',
  'Components/DecayCard': 'Hover parallax effect that disintegrates the content of a card.',
  'Components/Dock': 'macOS style magnifying dock with proximity scaling of icons.',
  'Components/DomeGallery': 'Immersive 3D dome gallery projecting images on a hemispheric surface.',
  'Components/ElasticSlider': 'Slider handle stretches elastically then snaps with spring physics.',
  'Components/FlowingMenu': 'Liquid flowing active indicator glides between menu items.',
  'Components/FluidGlass': 'Glassmorphism container with animated liquid distortion refraction.',
  'Components/FlyingPosters': '3D posters rotate on scroll infinitely.',
  'Components/Folder': 'Interactive folder opens to reveal nested content smooth motion.',
  'Components/GlassIcons': 'Icon set styled with frosted glass blur.',
  'Components/GlassSurface': 'Advanced Apple-style glass surface with real-time distortion + lighting.',
  'Components/GooeyNav': 'Navigation indicator morphs with gooey blob transitions between items.',
  'Components/InfiniteMenu': 'Horizontally looping menu effect that scrolls endlessly with seamless wrap.',
  'Components/InfiniteScroll': 'Infinite scrolling container auto-loads content near viewport end.',
  'Components/Lanyard': 'Swinging 3D lanyard / badge card with realistic inertial motion.',
  'Components/MagicBento': 'Interactive bento grid tiles expand + animate with various options.',
  'Components/Masonry': 'Responsive masonry layout with animated reflow + gaps optimization.',
  'Components/ModelViewer': 'Three.js model viewer with orbit controls and lighting presets.',
  'Components/PillNav': 'Minimal pill nav with sliding active highlight + smooth easing.',
  'Components/PixelCard': 'Card content revealed through pixel expansion transition.',
  'Components/ProfileCard': 'Animated profile card glare with 3D hover effect.',
  'Components/RollingGallery': '3D rolling gallery with drag controls.',
  'Components/ScrollStack': 'Overlapping card stack reveals on scroll with depth layering.',
  'Components/SpotlightCard': 'Dynamic spotlight follows cursor casting gradient illumination.',
  'Components/Stack': 'Layered stack with swipe animations and smooth transitions.',
  'Components/Stepper': 'Animated multi-step progress indicator with active state transitions.',
  'Components/TiltedCard': '3D perspective tilt card reacting to pointer.',
  'Components/StaggeredMenu': 'Menu with staggered item animations and smooth transitions on open/close.',

  // Backgrounds
  'Backgrounds/Aurora': 'Flowing aurora gradient background.',
  'Backgrounds/Balatro': 'The balatro shader, fully customizalbe and interactive.',
  'Backgrounds/Ballpit': 'Physics ball pit simulation with bouncing colorful spheres.',
  'Backgrounds/Beams': 'Crossing animated ribbons with customizable properties.',
  'Backgrounds/DarkVeil': 'Subtle dark background with a smooth animation and postprocessing.',
  'Backgrounds/Dither': 'Retro dithered noise shader background.',
  'Backgrounds/DotGrid': 'Animated dot grid with cursor interactions.',
  'Backgrounds/FaultyTerminal': 'Terminal CRT scanline squares effect with flicker + noise.',
  'Backgrounds/Galaxy': 'Parallax realistic starfield with pointer interactions.',
  'Backgrounds/GradientBlinds': 'Layered gradient blinds with spotlight and noise distortion.',
  'Backgrounds/GridDistortion': 'Warped grid mesh distorts smoothly reacting to cursor.',
  'Backgrounds/GridMotion': 'Perspective moving grid lines based on cusror position.',
  'Backgrounds/Hyperspeed': 'Animated lines continously moving to simulate hyperspace travel on click hold.',
  'Backgrounds/Iridescence': 'Slick iridescent shader with shifting waves.',
  'Backgrounds/LetterGlitch': 'Matrix style letter animation.',
  'Backgrounds/LightRays': 'Volumetric light rays/beams with customizable direction.',
  'Backgrounds/Lightning': 'Procedural lightning bolts with branching and glow flicker.',
  'Backgrounds/LiquidChrome': 'Liquid metallic chrome shader with flowing reflective surface.',
  'Backgrounds/Orb': 'Floating energy orb with customizable hover effect.',
  'Backgrounds/Particles': 'Configurable particle system.',
  'Backgrounds/PixelBlast': 'Exploding pixel particle bursts with optional liquid postprocessing.',
  'Backgrounds/Plasma': 'Organic plasma gradients swirl + morph with smooth turbulence.',
  'Backgrounds/Prism': 'Rotating prism with configurable intensity, size, and colors.',
  'Backgrounds/PrismaticBurst': 'Burst of light rays with controllable color, distortion, amount.',
  'Backgrounds/RippleGrid': 'A grid that continously animates with a ripple effect.',
  'Backgrounds/Silk': 'Smooth waves background with soft lighting.',
  'Backgrounds/Squares': 'Animated squares with scaling + direction customization.',
  'Backgrounds/Threads': 'Animated pattern of lines forming a fabric-like motion.',
  'Backgrounds/Waves': 'Layered lines that form smooth wave patterns with animation.',
  'Backgrounds/LiquidEther': 'Interactive liquid shader with flowing distortion and customizable colors.'
};
